### ISSUE TITLE
Trouble getting code working

### ISSUE THREAD

**Issue by JacobTyo** [BDBC-KG-NLP/Syntax-Encoding_EMNLP2018#2]
After trying to get the code running I ran into a few problems. One of which is the error: 

```
Traceback (most recent call last):                                                                      
  File "train.py", line 103, in <module>                                                                
    train()                                                                                             
  File "train.py", line 68, in train                                                                    
    output = model(text_test, syntax_test)                                                              
  File "/home/jtyo/Apps/anaconda3/envs/syntax_cnn/lib/python3.7/site-packages/torch/nn/modules/module.py
", line 547, in __call__                                                                                
    result = self.forward(*input, **kwargs)                                                             
  File "/home/jtyo/Repos/Syntax-Encoding_EMNLP2018/Pytorch-version/src/model.py", line 51, in forward   
    text_output = self.text_embedding(text)                                                             
  File "/home/jtyo/Apps/anaconda3/envs/syntax_cnn/lib/python3.7/site-packages/torch/nn/modules/module.py
", line 547, in __call__                                                                                
    result = self.forward(*input, **kwargs)                                                             
  File "/home/jtyo/Apps/anaconda3/envs/syntax_cnn/lib/python3.7/site-packages/torch/nn/modules/sparse.py
", line 114, in forward                                                                                 
    self.norm_type, self.scale_grad_by_freq, self.sparse)                                               
  File "/home/jtyo/Apps/anaconda3/envs/syntax_cnn/lib/python3.7/site-packages/torch/nn/functional.py", line 1467, in embedding       
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.ShortTe$
sor instead (while checking arguments for embedding)
```
Do you know how I can fix this? 

Thanks

**Comment by A-little-little-bird** [comment]
output = model(text_test, syntax_test)
It seems to be a data type error, the type of _test_test_  and _syntax_test_ should be Long.
